FROM python:3.9-slim

WORKDIR /app

COPY ./app /app/app
COPY requirements_api.txt /app/requirements_api.txt

RUN pip install --no-cache-dir -r requirements_api.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]