FROM python:3.9-slim

WORKDIR /app

COPY ./app /app/app
COPY requirements_api.txt /app/requirements_api.txt
COPY alembic.ini alembic.ini
COPY alembic alembic

RUN pip install --no-cache-dir -r requirements_api.txt