services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./shared_data:/app/shared_data
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=sqlite:////app/shared_data/tasks.db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./shared_data:/app/shared_data
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=sqlite:////app/shared_data/tasks.db
    working_dir: /app/worker_app
    command: ["python", "worker.py"]